### ISSUE TITLE
Not able to create a SHFB project at all!

### ISSUE THREAD

**Issue by mubed** [EWSoftware/SHFB#267] opened 2016-03-11 07:42 UTC
Using GUI, I'm not able to start any project at all:

``
Error reading project from 'D:\test\my.shfbproj': Object reference not set to an instance of an object.
``

In Visual Studio I'm able to create the project structure, but get the same error, when trying to build, open project properties or "ContentLayout.content":

``
Error		Unable to build project 'D:\dev\myProj\Documentation1\Documentation1.shfbproj': SandcastleBuilder.Utils.BuilderException: Error reading project from 'D:\dev\myProj\Documentation1\Documentation1.shfbproj':
Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at SandcastleBuilder.Utils.SandcastleProject.SetLocalProperty(String name, String value)
   at SandcastleBuilder.Utils.SandcastleProject.LoadProperties()
   --- End of inner exception stack trace ---
   at SandcastleBuilder.Utils.SandcastleProject.LoadProperties()
   at SandcastleBuilder.Utils.SandcastleProject..ctor(Project existingProject)
   at SandcastleBuilder.Utils.MSBuild.BuildHelp.Execute()	Documentation1	SHFB	0	
``

System info: Win7, VS2013, VS2015

**Comment by EWSoftware** [comment] 2016-03-11 16:05
Is this after just creating a brand new project or have you modified it in some way?  Can you attach the project file here so that I can take a look at it?

**Comment by mubed** [comment] 2016-03-19 06:41
How can I "create" an already existing project?!
There are two different cases here:
1. Using SHFB GUI, it is not possible to create any new project, so I can't send you anything that doesn't exist.
2. In VS, I am able to create a project, but I can't configure or build it. In this case, there is something I can send you, but currently I am on vacation, so you have to wait, but please don't close the issue.

**Comment by EWSoftware** [comment] 2016-03-19 18:39
In the standalone SHFB GUI, File | New Project will create a new project similar to Visual Studio except that you don't need to select a template, select the location and enter a name.

If I get no response within a reasonable amount of time, I close the issue.  Either it remains unanswered or it prompts the response I asked for.  I've reopened the issue as requested and will wait for an example.

One thing you can try is simply uninstalling SHFB, making sure the tools are gone from C:\Program Files (x86)\EWSoftware and the Tools | Extensions and Updates dialog, and reinstalling the latest version.  That may fix whatever was wrong if something was missing or corrupted.

**Comment by mubed** [comment] 2016-04-06 14:06
OK, I'm back again. Re-installing didn't work. I was already using the latest version.
As I said, using GUI, I'm not able to create any project at all, so there is nothing I can send you, but inside VS, I can create projects, but can't open them (see attachment)
[Documentation1.zip](https://github.com/EWSoftware/SHFB/files/206556/Documentation1.zip)

**Comment by EWSoftware** [comment] 2016-04-06 19:27
Your example works fine for me so something is probably wrong with your installation.  Have you tried it on a different PC?  A few things to do and check:

- Uninstall SHFB.
- Make sure that no files are left in *%ProgramFiles(x86)%\EWSoftware\Sandcastle Help File Builder*.  If there are, delete them.
- Make sure there are no virtualized copies of the SHFB files hanging around.  This can occur if you've manually replaced some of the installed files.  They can be located by looking in the *C:\Users\YOURACCOUNT\AppData\Local\VirtualStore\Program Files (x86)* folder (substitute your ID for "YOURACCOUNT"). You may see a *.\Sandcastle* and and/or *.\EWSoftware* folder. If so delete them.
- Make sure SHFBROOT doesn't exist as a system or user environment variable.  If you still find one after uninstalling, manually delete it.

After doing the above and reinstalling, make sure the SHFBROOT environment variable points to the installed location.  If it still doesn't work after that, I don't know what's wrong.

**Comment by mubed** [comment] 2016-04-07 12:22
- Uninstall SHFB.
  - Done
- Make sure that no files are left in %ProgramFiles(x86)%\EWSoftware\Sandcastle Help File Builder. If there are, delete them.
  - Nothing there
- Make sure there are no virtualized copies of the SHFB files hanging around. This can occur if you've manually replaced some of the installed files. They can be located by looking in the C:\Users\YOURACCOUNT\AppData\Local\VirtualStore\Program Files (x86) folder (substitute your ID for "YOURACCOUNT"). You may see a .\Sandcastle and and/or .\EWSoftware folder. If so delete them.
  - There is no folder "\VirtualStore"  there
- Make sure SHFBROOT doesn't exist as a system or user environment variable. If you still find one after uninstalling, manually delete it.
  -  I deleted it, rebooted and checked: was gone
- After doing the above and reinstalling, make sure the SHFBROOT environment variable points to the installed location. If it still doesn't work after that, I don't know what's wrong.
  - Reinstalled and checked the env variable: points to the correct folder

Then I ran the GUI and got the same error ("Object reference not set ...")

**Comment by EWSoftware** [comment] 2016-04-07 15:23
Sorry, like I said above.  If none of that fixes the issue.  I don't know what the problem is.  About all you can do if you're so inclined is download the code and debug it to see what it doesn't like on that particular system.

**Comment by mubed** [comment] 2016-04-07 17:50
OK,  thanks anyway.

**Comment by chriswallis** [comment] 2016-06-16 15:03
Mubed - did you manage to get over this?  I have the same version of SCHFB (2016.5.28.0) installed on two machines; Win 2010 and Server 2012 RC2.  Opening the same project, I get this error on the server but not on 2010.

**Comment by sandves** [comment] 2016-07-21 07:43
I have the exact same problem.

**Comment by EWSoftware** [comment] 2016-07-22 15:20
@mubed, @chriswallis , @sandves :  This is a long shot but do the failing machines have an environment variable defined that matches a [SHFB project property name](http://ewsoftware.github.io/SHFB/html/fee9df0c-7932-5edb-591f-5fa6ac512118.htm)?  If so, that may be causing the issue.  Note that the property doesn't have to exist in the actual project file.  The way properties work in MSBuild if an environment variables are included as properties so if the SHFB project sees one named the same it would try to use it.

If that's not the cause, then as noted above, unless someone is willing to run the standalone GUI under a debugger to see why it's failing, it's not something I can fix as I can't reproduce the issue.

**Comment by rossmills99** [comment] 2016-08-03 13:31
I am having the same issue.  I installed SHFB 16.5.28.0 on a build server, having recently updated our projects to use Visual Studio 2015.  We were successfully running an older version of SHFB on the same machine before I updated SHFB.  I get the error in the GUI and I see the following when running the build from command line, which includes some stack trace:

```
SHFB : error BHT0002: Unable to build project '{projectPath}': SandcastleBuilder.Utils.BuilderException: Error reading project from '{projectPath}': [{projectPath}]
SHFB : error BHT0002: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object. [{projectPath}]
SHFB : error BHT0002:    at SandcastleBuilder.Utils.SandcastleProject.SetLocalProperty(String name, String value) [{projectPath}]
SHFB : error BHT0002:    at SandcastleBuilder.Utils.SandcastleProject.LoadProperties() [{projectPath}]
SHFB : error BHT0002:    --- End of inner exception stack trace --- [{projectPath}]
SHFB : error BHT0002:    at SandcastleBuilder.Utils.SandcastleProject.LoadProperties() [{projectPath}]
SHFB : error BHT0002:    at SandcastleBuilder.Utils.SandcastleProject..ctor(Project existingProject) [{projectPath}]
SHFB : error BHT0002:    at SandcastleBuilder.Utils.MSBuild.BuildHelp.Execute() [{projectPath}]

```
(replaced all instances of project path with `{projectPath}`)

**Comment by rossmills99** [comment] 2016-08-03 13:39
Ah, I seem to have resolved this - after reading the preceding comment from EWSoftware (thanks!):

> do the failing machines have an environment variable defined that matches a SHFB project property name?

The answer was yes.  Besides SHFBROOT being set, I found there was a LANGUAGE environment variable set:

`LANGUAGE=C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\\Sandcastle Help File Builder\SandcastleBuilderGUI.exe`

After removing the `LANGUAGE` variable the build completes successfully.  I'm assuming this `LANGUAGE` variable was set by the SHFB installer itself though, so I'm unsure why it would break things...

**Comment by EWSoftware** [comment] 2016-08-03 15:24
No, the LANGUAGE environment variable wasn't set by SHFB or the installer.  It doesn't need it but would try to use it as the Language property in the project since MSBuild includes environment variables when it returns property values and they tend to override project properties.

This particular variable has caused a problem in the past and there's code in the project class to ignore errors related to it.  Not sure why it's causing a problem again.  I'll see if I can duplicate the problem.

**Comment by EWSoftware** [comment] 2016-08-03 15:29
I just noticed that the environment variable is in uppercase so that is probably the cause.  Issue #321 reported a similar issue with a different environment variable.  There is was trying to set a read-only property so it was easier to see what was causing the problem.  Resolving the case sensitivity issues should take care of this one too.

**Closed** 2016-08-20 22:04 UTC
Labels: Bug, BuildEngine
