### ISSUE TITLE
Issue with sample in office website

### ISSUE THREAD

**Issue by paradox2707** [EWSoftware/SHFB#810] opened 2020-08-12 23:00 UTC
Hello!
I have installed SHFB v2020.3.6.0 and tried to create *.chm for sample on your website https://ewsoftware.github.io/SHFB/html/d5dbf017-25f1-48cb-86db-90f76ee8f4d7.htm
but I have received fail
-------------------------------
[Sandcastle Help File Builder and Tools, version 2020.3.6.0]
Creating output and working folders...
Finding tools...
The Sandcastle tools are located in 'C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\'
Searching for HTML Help 1 compiler...
Found HTML Help 1 compiler in 'C:\Program Files (x86)\HTML Help Workshop\'
Locating components in the following folder(s):
    C:\Users\sluva\Desktop\test chm
    C:\ProgramData\EWSoftware\Sandcastle Help File Builder\Components and Plug-Ins\
    C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\
Using framework reflection data for '.NET Framework 4.8' located in 'C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\Data\.NETFramework'
Using presentation style 'VS2013' located in 'C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\PresentationStyles\VS2013'
Loading and initializing plug-ins...
Lightweight Website Style Version 2020.3.6.0
Copyright © 2006-2020, Eric Woodruff, All Rights Reserved
Portions Copyright © 2014, Sam Harwell, All Rights Reserved
-------------------------------
Validating and copying documentation source information
Source: C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleBuilder.WPF.xml
Source: C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleBuilder.WPF.dll
    Found assembly 'C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleBuilder.WPF.dll'

References to include:
    SandcastleBuilder.Utils

Copying XML comments files
    C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleBuilder.WPF.xml -> C:\Users\sluva\Desktop\test chm\Help\Working\SandcastleBuilder.WPF.xml
-------------------------------
Generating shared content files (en-US, English (United States))...
    Last step completed in 00:00:00,0200
-------------------------------
Generating API filter for MRefBuilder...
    Last step completed in 00:00:00,0090
-------------------------------
Generating reflection information...
[C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe - GenerateRefInfo.proj]
Build started 13.08.2020 1:53:31.
Project "C:\Users\sluva\Desktop\test chm\Help\Working\GenerateRefInfo.proj" on node 1 (default targets).
Project file contains ToolsVersion="15.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Microsoft.Common.targets(983,5): warning MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.8" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [C:\Users\sluva\Desktop\test chm\Help\Working\GenerateRefInfo.proj]
PrepareForBuild:
  Creating directory "obj\Debug\".
C:\Users\sluva\Desktop\test chm\Help\Working\GenerateRefInfo.proj(48,5): error MSB4002: There was a failure retrieving the attributes for parameters in the "Microsoft.Ddue.Tools.MSBuild.MRefBuilder" task. Could not load type 'Microsoft.Build.Framework.IBuildEngine5' from assembly 'Microsoft.Build.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
C:\Users\sluva\Desktop\test chm\Help\Working\GenerateRefInfo.proj(48,5): error MSB4060: The "Microsoft.Ddue.Tools.MSBuild.MRefBuilder" task has been declared or used incorrectly, or failed during construction. Check the spelling of the task name and the assembly name.
Done Building Project "C:\Users\sluva\Desktop\test chm\Help\Working\GenerateRefInfo.proj" (default targets) -- FAILED.

Build FAILED.

Time Elapsed 00:00:02.88
    Last step completed in 00:00:03,5460
-------------------------------

SHFB: Error BE0043: Unexpected error detected in last build step.  See build log for details.
   at SandcastleBuilder.Utils.BuildEngine.TaskRunner.Run(String processFilename, String targetFile, String arguments)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

**Comment by EWSoftware** [comment] 2020-08-12 23:29
Duplicate of #790.  Use Visual Studio to manage the project.  If you must use the standalone GUI, install the [Visual Studio 2017 Build Tools](https://download.visualstudio.microsoft.com/download/pr/3e542575-929e-4297-b6c6-bef34d0ee648/639c868e1219c651793aff537a1d3b77/vs_buildtools.exe).

**Closed by EWSoftware** 2020-08-12 23:29 UTC
Labels: Duplicate

**Comment by paradox2707** [comment] 2020-08-13 13:24
Thanks!
