### ISSUE TITLE
Encountered BE0065 when building a .NET Framework 4.8 project help file

### ISSUE THREAD

**Issue by jezzaSoup** [EWSoftware/SHFB#975] opened 2023-02-21 02:08 UTC
Trying to build the help file from a C# project (.NET Framework 4.8), and the BE0065 error was encountered:

`SHFB: Error BE0065: BUILD FAILED: Method not found: 'System.ReadOnlySpan1'<Char> Microsoft.IO.Path.GetFileName(System.ReadOnlySpan1'<Char>)'.`

![image](https://user-images.githubusercontent.com/107192303/220228820-b9f01f06-42c0-4a70-8f5e-3a2dcdf9b99b.png)

The documentation source information has been validated before the error was encountered. My help file builder GUI build mode is set to debug with AnyCPU. Re-installing the SHFB software didn't fix the issue; how could the issue be solved?

**Comment by EWSoftware** [comment] 2023-02-21 02:31
What version are you using?  This was an issue with earlier versions of the standalone GUI caused by an update to the build tools in Visual Studio 2022 but should be resolved in the latest release.  If you have the option, use Visual Studio as it doesn't have the problem.  Installing the MSBuild Tools for Visual Studio 2017 or 2019 can also work around the issue if you really need the standalone GUI.

**Comment by jezzaSoup** [comment] 2023-02-21 05:10
I currently have the Version 2022.1.22.0 builder GUI. Do you mean I can compile the help file straight from the Visual Studio 2022 IDE?

**Comment by jezzaSoup** [comment] 2023-02-21 05:42
Great success! The Visual Studio Integration Package compiled without any issue, and the help file is produced. Thanks for the help!

**Closed** 2023-02-21 15:22 UTC
