### ISSUE TITLE
Waring BHT0001 on TFS build server

### ISSUE THREAD

**Issue by ilgb** [EWSoftware/SHFB#252] opened 2016-02-15 12:19 UTC
When I build my solution on TFS build server with Visual Studio 2015 Update 1 I have this warning : 

> SHFB : warning BHT0001: Unable to get executing project:  Unable to obtain matching project from the global collection.  The specified project will be loaded but command line property overrides will be ignored.

I use latest SHFB version (v2015.10.10.0).

**Comment by EWSoftware** [comment] 2016-02-15 16:54
Duplicate of #208.  Fixed and will be included in the next release.  As noted in the original issue, it won't cause any problems unless you're overriding options from the command line.

**Closed by EWSoftware** 2016-02-15 16:54 UTC
Labels: Duplicate
