### ISSUE TITLE
Nuget packages don't get pulled in.

### ISSUE THREAD

**Issue by ristogod** [EWSoftware/SHFB#761] opened 2019-11-14 22:08 UTC
Using the new SDK, all nuget packages end up in this location

%USERPROFILE%\.nuget\packages

However, that could be different for every person that pulls this code from our git repo. So We can't add references to nuget package dlls needed to build our site.

**Comment by tom-englert** [comment] 2019-11-15 10:24
Isn't this a duplicate of #748?

**Comment by EWSoftware** [comment] 2019-11-15 20:12
I think it is and was going to suggest looking at that work item to see if the changes there apply here too.

**Closed** 2019-11-23 21:47 UTC
