### ISSUE TITLE
Error Building Documentation

### ISSUE THREAD

**Issue by LillithTChute** [EWSoftware/SHFB#608] opened 2018-05-23 16:14 UTC
I am trying to build a project relating to a .NET C# Web API.  The error I am getting says it is related to F Sharp, which I do not understand.  I have been circling this for some time now and am wondering if you might be able to help.  Here are the relevant error messages:

Building help topics...
[C:\Program Files (x86)\MSBuild\14.0\bin\amd64\MSBuild.exe - BuildTopics.proj]
Build started 5/23/2018 12:09:09 PM.
Project "C:\Development\Sandcastle Built Docs\Claim Detail Summary Report Service\Help\Working\BuildTopics.proj" on node 1 (default targets).
BuildTopics:
  BuildAssembler (v2018.5.14.0)
  Copyright c 2006-2018, Microsoft Corporation, All Rights Reserved.
  Portions Copyright c 2006-2018, Eric Woodruff, All Rights Reserved.
  Loading configuration...
BuildAssembler : error :  [C:\Development\Sandcastle Built Docs\Claim Detail Summary Report Service\Help\Working\BuildTopics.proj]
BuildAssembler : error : CopyFromIndexComponent: The indexed document 'C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.4.3.0\FSharp.Core.xml' is not a valid XML document. The error message is: The 'member' start tag on line 5887 position 2 does not match the end tag of 'returns'. Line 5900, position 4. [C:\Development\Sandcastle Built Docs\Claim Detail Summary Report Service\Help\Working\BuildTopics.proj]
BuildAssembler : error :  [C:\Development\Sandcastle Built Docs\Claim Detail Summary Report Service\Help\Working\BuildTopics.proj]
BuildAssembler : error : BuildAssemblerCore: An unexpected error occurred while attempting to create the build component 'Copy From Index Component'. The error message is: One or more errors occurred. [C:\Development\Sandcastle Built Docs\Claim Detail Summary Report Service\Help\Working\BuildTopics.proj]
BuildAssembler : error :  [C:\Development\Sandcastle Built Docs\Claim Detail Summary Report Service\Help\Working\BuildTopics.proj]
BuildAssembler : error : BuildAssemblerCore: An unexpected error occurred while attempting to create the build component 'Switch Component'. The error message is: See log for details [C:\Development\Sandcastle Built Docs\Claim Detail Summary Report Service\Help\Working\BuildTopics.proj]
Done Building Project "C:\Development\Sandcastle Built Docs\Claim Detail Summary Report Service\Help\Working\BuildTopics.proj" (default targets) -- FAILED.

Build FAILED.

Thank You!

Lillith

**Comment by EWSoftware** [comment] 2018-05-23 19:11
Duplicate of #604.  See it for the workaround.  A new release this weekend will fix this.

**Closed by EWSoftware** 2018-05-23 19:11 UTC
