### ISSUE TITLE
Standalone GUI reports invalid project file format

### ISSUE THREAD

**Issue by Hefaistos68** [EWSoftware/SHFB#831] opened 2020-12-30 12:37 UTC
I have a VS2019 solution with 13 C# projects, .NET Core 3.1, and a documentation project. 4 C# projects are included as Documentation source.
The doc project compiles fine, I can edit it as usual. Yet when I try to open the project in the Standalone GUI, I get the following error message and the project is not loaded.

> ---------------------------
> Sandcastle Help File Builder
> ---------------------------
> The project file format is invalid: The tools version "15.0" is unrecognized. Available tools versions are "2.0", "3.5", "4.0".  C:\...\source\Workspaces\Q7\Q7\Q7 Documentation\Q7 Documentation.shfbproj
> 

The only thing with version 15 I see is the Microsoft.Build assembly, which is 15.1.0.0.
Using the latest SHFB version 2020.3.6.0

**Comment by EWSoftware** [comment] 2020-12-30 17:12
Duplicate of #797.  It's fixed and the changes have been checked in. I just haven't published a new release containing the fix. For now, the same workaround applies: Use the Visual Studio package or install the VS 2015 tools if you really need the standalone GUI.

**Closed** 2020-12-30 17:15 UTC
Labels: Duplicate
