### ISSUE TITLE
EWSoftware.SHFB.UniversalWindows not working with Visual Studio 2015 Update 3

### ISSUE THREAD

**Issue by shawnhar** [EWSoftware/SHFB#322] opened 2016-08-03 19:54 UTC
My Sandcastle project (https://github.com/Microsoft/Win2D/blob/master/tools/docs/BuildDocs.shfbproj) builds documentation for a UWP framework by specifying:

    <FrameworkVersion>.NET for Universal Windows</FrameworkVersion>

I build this using the two NuGet packages:

    EWSoftware.SHFB" version="2016.5.28
    EWSoftware.SHFB.UniversalWindows" version="1.0.0

Upon upgrading to Visual Studio 2015 Update 3, my build, which was previously working against Update 2, is now failing with the error:

```
GenerateRefInfo:
  MRefBuilder (v2016.5.28.0)
  Copyright c 2006-2016, Microsoft Corporation, All Rights Reserved.
  Portions Copyright c 2006-2016, Eric Woodruff, All Rights Reserved.
MRefBuilder : error : An unexpected error occurred trying to execute the MRefBuilder MSBuild task: System.InvalidOperationException: Unable to locate information for the framework version &#39;.NETCore 5.0&#39; or a suitable redirected version on this system [F:\Win2D\Enlistment\bin\docs\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at System.Compiler.TargetPlatform.SetFrameworkInformation(String platformType, String version, IEnumerable`1 componentLocations) [F:\Win2D\Enlistment\bin\docs\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.MRefBuilderCore.Main(String[] args) [F:\Win2D\Enlistment\bin\docs\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.MSBuild.MRefBuilder.Execute() [F:\Win2D\Enlistment\bin\docs\Working\GenerateRefInfo.proj]
Done Building Project &quot;F:\Win2D\Enlistment\bin\docs\Working\GenerateRefInfo.proj&quot; (default targets) -- FAILED.
```

Any ideas?  Do I need a new version of the UniversalWindows package to support whatever has changed about .NETCore in VS Update 3?

**Comment by EWSoftware** [comment] 2016-08-04 15:15
It looks like Update 3 removes the SDK files that the reflection data set is using.  New projects appear to add the framework via a NuGet package.  I'll have to see if I can create a new data set file that references the NuGet folder instead.

**Comment by dkemlage** [comment] 2016-08-11 16:58
Hello Eric,

My company is experiencing the same thing. Apparently, moving to Visual Studio 2015 Update 3 does something that SandCastle (v2016.5.28.0) does not like when trying to build API Reference documents on Windows Universal Windows Platform (UWP) based .dll’s. This problem does not exist for the Visual Studio 2015 Update 2 and SandCastle (v2016.5.28.0) configuration.

Here are some reproducible steps:

**ONE:** Use VS2015 (update 3) to create a Windows Universal Class Library. Make sure and check on building XML documentation in the Project Properties. Set the Target Version and Minimum Version to be _Windows 10 (10.0; Build 10586)_ in the New Universal Windows Project dialog.

**TWO:** Replace the code for Class1.cs with the following:
```
namespace ClassLibrary_UWP
{

    /// <summary>
    /// This is Class1. It is a test.
    /// </summary>
    public class Class1
    {
        /// <summary>
        /// This is TestMehod. It is a test.
        /// </summary>
        public void TestMethod()
        {
        }
    }
}
```

**THREE:** Build the project to create the ClassLibrary_UWP.dll
 
**FOUR:** Create a VS2015 (update 3) SandCastle documentation project.

**FIVE:** Reference the ClassLibrary_UWP.dll as a documentation source. 

**SIX:** Change the Framework version to ".NET for Universal Windows" in the documentation project's Properties dialog | Build tab.

**SEVEN:** Build the project, wait for the compile to fail, and examine the LastBuild.log file. The contents should contain something like:

```
GenerateRefInfo:
  MRefBuilder (v2016.5.28.0)
  Copyright c 2006-2016, Microsoft Corporation, All Rights Reserved.
  Portions Copyright c 2006-2016, Eric Woodruff, All Rights Reserved.
MRefBuilder : error : An unexpected error occurred trying to execute the MRefBuilder MSBuild task: System.InvalidOperationException: Unable to locate information for the framework version &#39;.NETCore 5.0&#39; or a suitable redirected version on this system [C:\temp\SandCastle_VisualStudioUpdate3\SandCastle_VisualStudioUpdate3\SandCastle2016_5_28_0_TestProject\SandCastle2016_5_28_0_TestProject\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at System.Compiler.TargetPlatform.SetFrameworkInformation(String platformType, String version, IEnumerable`1 componentLocations) [C:\temp\SandCastle_VisualStudioUpdate3\SandCastle_VisualStudioUpdate3\SandCastle2016_5_28_0_TestProject\SandCastle2016_5_28_0_TestProject\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.MRefBuilderCore.Main(String[] args) [C:\temp\SandCastle_VisualStudioUpdate3\SandCastle_VisualStudioUpdate3\SandCastle2016_5_28_0_TestProject\SandCastle2016_5_28_0_TestProject\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.MSBuild.MRefBuilder.Execute() [C:\temp\SandCastle_VisualStudioUpdate3\SandCastle_VisualStudioUpdate3\SandCastle2016_5_28_0_TestProject\SandCastle2016_5_28_0_TestProject\Help\Working\GenerateRefInfo.proj]
Done Building Project &quot;C:\temp\SandCastle_VisualStudioUpdate3\SandCastle_VisualStudioUpdate3\SandCastle2016_5_28_0_TestProject\SandCastle2016_5_28_0_TestProject\Help\Working\GenerateRefInfo.proj&quot; (default targets) -- FAILED.

Build FAILED.
```

FYI, copying the same UWP and SandCastle test projects (mentioned above) to a machine with only Visual Studio 2015 (update 2) and running the SandCastle build works fine and produces a .CHM/website documentation.

Unfortunately, once you go down the Visual Studio update path (even inadvertently), it becomes VERY difficult to go back to an older update. Looking forward to a fix as soon as you get the time!

Thanks,
Don Kemlage

**Comment by EWSoftware** [comment] 2016-08-11 19:12
As noted above, Update 3 changes the prior SDK locations.  Instead it puts them in a NuGetPackages SDK folder.  Attached below are the two new reflection data set definition files.  Extract and drop them in the *Data\UniversalWindows* folder in the SHFB installation folder.  The two files distinguished from the originals by a "(NuGet)" suffix in their title should resolve the issue.

I haven't had a chance to rebuild the SHFB UWP reflection data set NuGet package so for now, dropping the two files in the equivalent package folder should workaround the issue for the time being.

[UWPReflection.zip](https://github.com/EWSoftware/SHFB/files/414012/UWPReflection.zip)

**Comment by dkemlage** [comment] 2016-08-11 23:31
Hello Eric,
I just tested the fix and it worked perfectly!
Thank you for being so responsive.
-Don Kemlage

**Closed** 2016-08-20 22:04 UTC
Labels: SandcastleTools

**Comment by shawnhar** [comment] 2016-09-06 14:56
Many thanks for fixing this, it's much appreciated!

Any ETA for the next Sandcastle release?  (I assume that's when you will update NuGet packages to include this fix?)

**Comment by EWSoftware** [comment] 2016-09-06 15:35
I'll publish a new release in a week or two.
