### ISSUE TITLE
Markdown output links broken

### ISSUE THREAD

**Issue by tylercamp** [EWSoftware/SHFB#499] opened 2017-08-09 15:35 UTC
When I generate Markdown content and host it on Github, links between pages are broken as the link references include the ID of the topic, but not the .md extension. Navigating to a page returns 404 not-found, but if I add .md to the end of the address it works perfectly.

**Comment by EWSoftware** [comment] 2017-08-09 16:54
Duplicate of #360.  Refer to it for details.

**Closed by EWSoftware** 2017-08-09 16:54 UTC
Labels: Duplicate

**Comment by tylercamp** [comment] 2017-08-09 17:41
The linked issue states that hosting on Github will give proper navigation, but I'm not finding that to be the case. Hosting my markdown docs on GitHub without the .md extension gives me Not Found when clicking on a link to another markdown page.

Maybe github changed their markdown behavior? Or is there something I'm missing?

**Comment by EWSoftware** [comment] 2017-08-09 19:10
In the wiki or in source control file view?  If in the wiki it should work fine as shown by the spellchecker project's wiki.  In the wiki, the presence of the extension causes it to go to the raw content as noted.  In source control file view, it's shown the actual files so it does want the extensions there.
