### ISSUE TITLE
The tools version "15.0" is unrecognized.

### ISSUE THREAD

**Issue by cwieczorrek** [EWSoftware/SHFB#790] opened 2020-03-25 08:00 UTC
Hello,
I am using SHFB for many years without any problems.

Two weeks ago I got a new, clear laptop with Windows 10 Enterprise 1909.
I installed Visual Studio 2019. I copied all my projects to disc. All projects compile and run without problems.

But trying to create a new helpfile results in the error

The tools version "15.0" is unrecognized. Available tools versions are "2.0", "3.5", "4.0".

for ALL projects. No SHFB project compiles.

Yersterday I did the Visual Studio update to 16.5.0. This morning I got a new update to 16.5.1. Nothing changes.

I am using SHFB v20203.6.0. My projects compile for FrameWork 4.5 up to 4.7.2.

Any idea?

Sincerely
Carsten Wieczorrek

**Comment by EWSoftware** [comment] 2020-03-25 19:32
That typically means you haven't got an appropriate version of MSBuild installed or it's not finding it for some reason.  I can't say why that might be.  Google "tools version 15.0 unrecognized" and it turns up several hits.  I'd start there and see if any of those can help resolve your issue.

**Comment by cwieczorrek** [comment] 2020-03-26 06:42
Hello Eric,

thanks for your answer.

I did this search yersterday and I tried two or three "solutions" without 
success.
I am just wondering because it is a new "fresh" laptop with a new 
VisualStudio 2019 installation. There is no older version installed. A 
conflict between two different MSBuild versions should not be possible.

Thanks for your help,


Stay healthy or become imune ;-)

Carsten

**Comment by cserl** [comment] 2020-03-26 20:38
Hello,

I can confirm, I get the same error message from Sandcastle upon File > New Project: "The tools version "15.0" is unrecognized. Available tools versions are "2.0", "3.5", "4.0".

Fresh install of Visual Studio 2019 16.5.1 Community Edition.

Best Regards
L

**Comment by 304NotModified** [comment] 2020-03-28 15:36
Same issue here.  Visual Studio 2019. In my path I have msbuild version 16:

    Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Framework

**Comment by EWSoftware** [comment] 2020-03-28 18:14
Sorry, don't know what to tell you.  I can run that version explicitly with a SHFB project in which the tools version attribute is set to 15.0 or otherwise and it works.  As a workaround, you can try setting the tools version in the project to something else like 4.0.

**Comment by 304NotModified** [comment] 2020-03-28 19:00
How does it search for version 15? In the registery?

**Comment by 304NotModified** [comment] 2020-03-28 19:01
The problem is that SHFB generates GenerateRefInfo.proj, and then chokes on it. Dunno how to fix that.

**Comment by EWSoftware** [comment] 2020-03-28 20:21
I thought this was when opening or building the actual SHFB project, not the subprojects it uses in the build.  That can't be worked around.  To see if I can reproduce this, I'll probably need to create a VM with only VS2019 installed.  I don't have time right now so it may be a while.

**Comment by 304NotModified** [comment] 2020-03-28 20:49
If there is something I could help to diagnose the issue, let me know

**Comment by srupprecht1** [comment] 2020-03-31 00:08
I have the same issue when trying to save a new project to file. Product components list in SHFB shows MS Build 15.1.

**Comment by 304NotModified** [comment] 2020-03-31 18:30
maybe related, but not sure: https://github.com/Microsoft/msbuild/issues/2427 + https://docs.microsoft.com/en-us/visualstudio/msbuild/updating-an-existing-application

**Comment by EWSoftware** [comment] 2020-04-01 01:50
It could be the MSBuild package references.  I'm using version 15.9.20.  The second link you posted suggests using 15.1.548 for VS2017 and later.  Either that or switching to the MSBuild locator package it also references.  Not sure that makes a difference though as this issue is with VS2019.

Note also that this release does distribute the MSBuild assemblies locally with SHFB.  The prior release did not which caused issues with missing reference assemblies which is why I included them this time.  Simply removing them from the distributed set may also resolve this issue.

**Comment by abcolson** [comment] 2020-04-01 23:16
I installed Visual Studio 2019 about a month ago (along side previous versions).
Yesterday, I upgraded SHFB to the latest version.  Prior to upgrading I could build help files within SHFB GUI; after upgrade, I could not.

I can create a VS 2019 project.  When I build, things seem to be Ok (still getting errors which I think are unrelated).  The logging comments are

5>------ Build started: Project: UnitTests Documentation, Configuration: Debug Any CPU ------
5>		Building D:\dev\MMIS\MMIS.Core\UnitTests Documentation\UnitTests Documentation.shfbproj
5>		Initializing
5>		ClearWorkFolder
5>		ValidatingDocumentationSources
5>		GenerateSharedContent
5>		GenerateApiFilter
5>		GenerateReflectionInfo
5>		TransformReflectionInfo
5>		GenerateNamespaceSummaries
5>		CopyConceptualContent
5>		CreateConceptualTopicConfigs
5>		CopyAdditionalContent
5>		MergeTablesOfContents
5>		GenerateIntermediateTableOfContents
5>		CreateBuildAssemblerConfigs
5>		MergeCustomConfigs
5>		BuildTopics
etc.

But when built within SHFB GUI there are problems at GenerateReflectionInfo:

SHFB: Error BE0065: BUILD FAILED: The tools version "15.0" is unrecognized. Available tools versions are "14.0", "2.0", "3.5", "4.0".  D:\dev\MMIS\MMIS.Core\UnitTests Documentation\Help\Working\GenerateRefInfo.proj

Apparently, MS Build is no longer put into the GAC and is instead part of each Visual Studio installation as of VS 2017.

So, my question is (and maybe this can lend some insight) "Why does this work in Visual Studio 2019 but not in SHFB GUI?  What is VS 2019 doing to allow SHFB to access the correct MS Build that is not happening if I run directly from the SHFB GUI?

Thanks
Tony

**Comment by cwieczorrek** [comment] 2020-04-02 07:01
Hello,
same to me. I used SandCastle this morning the first time from inside visual studio. And it compiles my project!
From the GUI it fails.

Carsten

**Comment by EWSoftware** [comment] 2020-04-04 22:19
I created a VM and installed VS2019 and SHFB.  Visual Studio works fine.  It's only the standalone GUI that is failing.  The reason Visual Studio works is that it hosts its own copy of MSBuild as I understand it.  As such, when SHFB looks at the tools collection for the latest version, it finds the one being used by Visual Studio.  The standalone GUI does the same thing (look for the latest tool set) but in that case, the path for the two versions present (4.0 and 15.0) are the same and both point to the 4.0 version in the .NET Framework folder.

So, for now, if you have Visual Studio, use it.  The standalone GUI is only there for people that don't have Visual Studio anyway so there's really no need to use it if you've got Visual Studio.

**Comment by abcolson** [comment] 2020-04-06 17:34
One reason I like using the GUI is because it has previewing options (which maybe I missed in Visual Studio).

**Comment by abcolson** [comment] 2020-04-06 17:37
I just want to say, Eric, that I think you have done an incredibly good job with the whole project.  Thank you!

**Comment by EWSoftware** [comment] 2020-04-06 18:11
@abcolson All of the options in the standalone GUI are available in the Visual Studio extension.  The viewing options can be found under View | View Help file.  The [Feature Comparison and Location](http://ewsoftware.github.io/SHFB/html/78507051-0fc0-479b-9d47-78a10398eaf2.htm) help topic gives an overview of where stuff is at compared to the standalone GUI.  If you can't find something, let me know.

**Comment by abcolson** [comment] 2020-04-06 22:03
Thanks Eric!  The Topic Previewer was what I was missed.  Seems to work great!
   This e-mail and any files transmitted with it may contain privileged and confidential information and are intended solely for the use of the individual or entity to which they are addressed. If you are not the intended recipient or the person responsible for delivering the e-mail to the intended recipient, you are hereby notified that any dissemination or copying of this e-mail or any of its attachment(s) is strictly prohibited. If you have received this e-mail in error, please immediately notify the sending individual or entity by e-mail and permanently delete the original e-mail and attachment(s) from your computer system. Thank you.

**Comment by VBWebprofi** [comment] 2020-07-23 19:10
MSBuild 15.0 is part of VS 2017. You can download on

https://my.visualstudio.com/Downloads?q=visual%20studio%202017&wt.mc_id=o~msft~vscom~older-downloads .

For Installation select Visual C++ Buildtools and unselect on right pane all optionals.

**Comment by mickeysuda** [comment] 2020-08-03 03:05
Resolved by installing [VS 2017 Build Tools Installer](https://download.visualstudio.microsoft.com/download/pr/3e542575-929e-4297-b6c6-bef34d0ee648/639c868e1219c651793aff537a1d3b77/vs_buildtools.exe)

**Comment by cwieczorrek** [comment] 2020-08-03 05:12
Hello,
@mickeysuda : I confirm. It is working now. Thank you.

Carsten

**Comment by goyzhang** [comment] 2020-08-03 05:24
> Hello,
> @mickeysuda : I confirm. It is working now. Thank you.
> 
> Carsten

But that's a work around right? Why do I have to install VS2017 Build Tools to be able to start SandcastleBuilderGUI 😋.

**Comment by mickeysuda** [comment] 2020-08-03 06:10
> 
> 
> > Hello,
> > @mickeysuda : I confirm. It is working now. Thank you.
> > Carsten
> 
> But that's a work around right? Why do I have to install VS2017 Build Tools to be able to start SandcastleBuilderGUI 😋.

Not really look into very detail on implementation, according to [Installation Instructions > Requirements](https://ewsoftware.github.io/SHFB/html/8c0c97d0-c968-4c15-9fe9-e8f3a443c50a.htm#Requirements), i also assumed VS2019 installed with msbuild 16 should be okay, but not lucky to make GUI work.

**Comment by goyzhang** [comment] 2020-08-03 07:44
I think this is not a SHFB issue, after upgrading the Microsoft.Build from 15.9.20 to 16.6.0. The `InvalidProjectFileException` which eventually causes the error is gone. So maybe we should simply upgrade the reference?

**Comment by EWSoftware** [comment] 2020-08-03 16:02
If you are using a version of Visual Studio or MSBuild less than 2017, you need to install the 2017 build tools.  If using 2017 or later you don't need to.  Upgrading the references doesn't solve the issue and is what caused the problem in the current release.  The solution for 2017 and later is to reference the lowest common version of the assemblies and use the [Microsoft.Build.Locator](https://docs.microsoft.com/en-us/visualstudio/msbuild/updating-an-existing-application?view=vs-2019) to find and load the actual assemblies at startup.  As noted above, this only affects the standalone GUI.  So, while all SHFB tool projects need to be updated with the same version of the references, the standalone GUI is the only one that needs to use the locator when it starts up to find and load the assemblies for building the projects.  The fix will be in the next release, probably sometime in September.

**Comment by mikasoukhov** [comment] 2020-08-03 16:08
Clean machine. VS 2019 only. Same issue. Seems the issue in SHFB. Not in multiple MSBuild versions installed on the PC.

**Comment by EWSoftware** [comment] 2020-08-03 16:22
@mikasoukhov  That's [already known](https://github.com/EWSoftware/SHFB/issues/790#issuecomment-609096630).  The solution as noted above is to update it to use the build locator.

**Comment by mikasoukhov** [comment] 2020-08-03 16:45
> @mikasoukhov That's [already known](https://github.com/EWSoftware/SHFB/issues/790#issuecomment-609096630). The solution as noted above is to update it to use the build locator.

Can you please provide the exact config file?

**Comment by EWSoftware** [comment] 2020-08-03 17:57
It'll be changes to the references in the projects used to build the tools and some code changes in the standalone GUI.  They haven't been done yet.

**Comment by mikasoukhov** [comment] 2020-08-04 10:38
> It'll be changes to the references in the projects used to build the tools and some code changes in the standalone GUI. They haven't been done yet.

ok. VS Integration do not work as well in the latest release.

**Comment by EWSoftware** [comment] 2020-08-04 14:18
How so?  It works the same as it always has.

**Comment by mikasoukhov** [comment] 2020-08-04 15:09
No. It works with 2017 only. If a machine does not this VS no VSIP neither UI do not work.

**Comment by EWSoftware** [comment] 2020-08-05 01:11
It works in VS 2019 as well even if that's only thing installed.  The VM I used to diagnose the standalone GUI problem only has VS2019 and it works fine within Visual Studio.

**Closed** 2020-08-28 14:31 UTC

**Comment by codeswayslay** [comment] 2020-09-02 08:40
To anyone still having this annoying error, even with Visual Studio 2019, please refer to this link: https://ewsoftware.github.io/SHFB/html/63e7d1c3-6706-444b-aa02-5defd7d1da60.htm
There's a section with the link to the build tools you can download: https://www.microsoft.com/en-us/download/details.aspx?id=48159

Honestly, I'm shocked that this issue (and a properly described resolution) isn't captured in the installation guide. I see people on here saying "use Visual Studio to generate your documentation", but the Sandcastle Visual Studio extension is a nightmare to use. The only way to use Sandcastle properly is with the Builder GUI. 

I'd suggest that the engineers add this issue and its resolution to their installation guide to help future users.
