### ISSUE TITLE
SHFB: Error BE0065: BUILD FAILED: The &#39;br&#39; start tag on line 977 position 39 does not match the end tag of &#39;p&#39;. Line 977, position 153

### ISSUE THREAD

**Issue by JJoe2** [EWSoftware/SHFB#589] opened 2018-03-30 20:37 UTC
Windows 10
Visual Studio Professional 2017 Version 15.6.4
SHFB 2017.12.30.2

I've created a .NET Standard Class Library that references the System.Configuration.ConfigurationManager 4.4.1 NuGet package.

Plus a SHFB project that references it as a Documentation source.

SHFB build fails with the error below.
No indication in the log of which file caused this error.

<buildStep step="GenerateNamespaceSummaries">
Generating namespace summary information...
    Last step completed in 00:00:00,0206
</buildStep>
<buildStep step="Failed">

SHFB: Error BE0065: BUILD FAILED: The &#39;br&#39; start tag on line 977 position 39 does not match the end tag of &#39;p&#39;. Line 977, position 153.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
   at System.Xml.XmlTextReaderImpl.ParseEndElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at SandcastleBuilder.Utils.BuildEngine.XmlCommentsFile.get_Comments()
   at SandcastleBuilder.Utils.BuildEngine.XmlCommentsFile.get_Members()
   at SandcastleBuilder.Utils.BuildEngine.XmlCommentsFileCollection.get_ContainsInheritedDocumentation()
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

</buildStep>

**Comment by EWSoftware** [comment] 2018-03-30 23:15
Duplicate of #574, #569, and #560.  See any of them for the workaround until the next release.

**Closed by EWSoftware** 2018-03-30 23:15 UTC

**Comment by JJoe2** [comment] 2018-03-31 09:41
I looked at the linked issues, but am still unable to resolve the problem.
- My project references only System.Configuraiton.ConfigurationManager and netstandard2.0
- The System.Configuration.ConfigurationManager NuGet package on my disk does not have an XML file.
- I have added both System.Configuration.ConfigurationManager  and netstandard to Plug-Ins > Assembly Binding Redirection > Ignore if unresolved

The offending project is attached,
[SingleTargeting.zip](https://github.com/EWSoftware/SHFB/files/1865338/SingleTargeting.zip)

**Comment by EWSoftware** [comment] 2018-03-31 20:07
The assembly binding redirection plug-in reference was related to ignoring a missing assembly, not a bad XML comments file.
