### ISSUE TITLE
Namespace Summaries are not always applied when using Version Builder

### ISSUE THREAD

**Issue by swirlywonder** [EWSoftware/SHFB#347] opened 2016-10-04 21:46 UTC
There is an issue when using Version Builder where summaries declared in the project file are not always applied to the output.

I've been able to isolate the exact cause and how to reproduce:

1. The help project files referenced by the Version Builder plug-in contain comment files (i.e. a MyAssembly.xml for each version). This approach should be valid and allow merging of old apis into new ones.
2. This scenario produces multiple `XmlCommentsFile` entries (Note: the same namespaces may be present in other files)
3. `XmlCommentsFileCollection.FindMember()` looks for the _first_ match only. Therefore namepace summaries will not be applied to the all versions. Since the first match may not necessarily be for the "current project", those namespace summaries are omitted from the final output.

**Comment by EWSoftware** [comment] 2016-10-14 21:35
Everything appears to be working as designed.  As noted in the plug-in's documentation, the reference projects are there only to provide reflection information and as such only go through a partial build.  Partial builds stop before handling any of the documentation project's summary/namespace comments so as noted, they are ignored.

If you open the Namespace Summaries dialog in the containing project, you will see a complete list of all namespaces from all assemblies.  That's were you should put the namespace comments.  This is appropriate since you wouldn't necessarily want comments from a prior release replacing or being merged with the comments from the most recent release.

An exception is `NamespaceDoc` classes.  Comments from those are generated by the compiler and SHFB converts them to namespace comment entries.  As such, they will show up and potentially be merged with the namespace comments from the containing project.

**Closed** 2016-10-21 02:00 UTC
