### ISSUE TITLE
NullReferenceException when adding a file-less content node

### ISSUE THREAD

**Issue by bleachpuppy** [EWSoftware/SHFB#559] opened 2018-01-08 20:55 UTC
I recently upgraded to v2017.12.30.0 (I don't know what I had before but it was probably from around a year earlier), and I get this message:
```
SHFB : error BE0029: Unexpected error while executing plug-in 'Lightweight Website Style': System.AggregateException:
One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
```
I tracked it down and after a lot of trial and error, it looks like it's due to a node in a .content file that does not have a matching .aml file, i.e. a Topic node with attribute "noFile=true".  To reproduce, I found a shfb project that was working with the new version (the project had no empty topics), and from the content layout editor gui I clicked "Add Empty Container Topic", and that reproduced the NullReferenceException in 'Lightweight Website Style' above.

(I also see this same thing referenced under issue #556)

**Comment by EWSoftware** [comment] 2018-01-08 22:00
Duplicate of #556.  A new release will be available shortly.

**Closed by EWSoftware** 2018-01-08 22:00 UTC
