### ISSUE TITLE
Markdown file suffixes in links

### ISSUE THREAD

**Issue by moethu** [EWSoftware/SHFB#148] opened 2015-07-17 10:44 UTC
Hi there,
first of all, thank you for this great project. Makes documenting things way easier.

Since I'm a lazy person I'd like to browse the compiled markdown documentation on github directly. This works out fine except for links, they are missing the ".md" suffix. If I'm following a link in the markdown document github throws 404 until I add ".md" to the URL manually. Is there any solution for that? Am I missing something?
![2015-07-17_11h40_39](https://cloud.githubusercontent.com/assets/8201465/8745539/d5e44ace-2c78-11e5-8cd3-575b3d33187a.png)

Thank you for your help.

**Comment by sharwell** [comment] 2015-07-17 12:22
Hi @moethu,

Thanks for taking the time to try out this presentation style and provide feedback.

This issue is actually a duplicate of #143; you may find additional information about it in the comments there.

**Comment by EWSoftware** [comment] 2015-07-17 15:08
As noted in #143, the output is intended for wiki sites, not the source repository.  I could add the extensions but even then, there's no guarantee the content would work as expected in all cases.

**Closed by EWSoftware** 2015-07-17 15:08 UTC
