### ISSUE TITLE
SHFB: Error BE0065: BUILD FAILED: The tools version "15.0" is unrecognized.

### ISSUE THREAD

**Issue by DiskCrasher** [EWSoftware/SHFB#814] opened 2020-09-08 18:26 UTC
SHFB v2020.3.6.0 getting this error on my Visual Studio 2019 projects:

**SHFB: Error BE0065: BUILD FAILED: The tools version "15.0" is unrecognized. Available tools versions are "14.0", "2.0", "3.5", "4.0".** 

My .csproj file contains the following line:

`<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">`

Changing this to 14.0 works but that doesn't seem like the right solution. It would also require me to change all my projects.

**Comment by EWSoftware** [comment] 2020-09-09 23:53
Duplicate of #797. Fixed for the next release due out later this month.  In the meantime, use Visual Studio 2019 to build the projects or if you are using the standalone GUI, install the Visual Studio 2017 build tools.  See the other work item for details.

**Closed by EWSoftware** 2020-09-09 23:53 UTC
