### ISSUE TITLE
Failure to launch Help File Builder GUI with only VS2017 installed

### ISSUE THREAD

**Issue by dotMorten** [EWSoftware/SHFB#478] opened 2017-06-02 06:50 UTC
If you only have VS2017 installed, this happens: 
![image](https://cloud.githubusercontent.com/assets/1378165/26714120/e2965302-4724-11e7-9eae-9c6cfa640151.png)

It's trying to load the v14 version of Microsoft.Build which only comes with VS2015.
You can hit continue, and the app launches, but you keep getting similar exceptions over and over again.

Full output
```

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at SandcastleBuilder.Gui.MainForm.MainForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].



************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
SandcastleBuilderGUI
    Assembly Version: 2016.4.9.0
    Win32 Version: 17.5.15.0
    CodeBase: file:///C:/Program%20Files%20(x86)/EWSoftware/Sandcastle%20Help%20File%20Builder/SandcastleBuilderGUI.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2094.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2093.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2093.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
SandcastleBuilder.Utils
    Assembly Version: 2016.4.9.0
    Win32 Version: 17.5.15.0
    CodeBase: file:///C:/Program%20Files%20(x86)/EWSoftware/Sandcastle%20Help%20File%20Builder/SandcastleBuilder.Utils.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 2.8.0.1
    Win32 Version: 2.8.0.1
    CodeBase: file:///C:/Program%20Files%20(x86)/EWSoftware/Sandcastle%20Help%20File%20Builder/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by netx123** [comment] 2017-06-02 10:17
This is mentioned in the latest release notes: [2017.5.15.0 Release Notes](http://ewsoftware.github.io/SHFB/html/63e7d1c3-6706-444b-aa02-5defd7d1da60.htm)

You need to install the [Microsoft Build Tools 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48159).

**Comment by dotMorten** [comment] 2017-06-03 00:42
Thanks. Your installer is really good at detecting missing components. Might be worth adding as a check? Alternatively have you considered compiling it with non-specific version?

Btw that link is dead.

**Comment by EWSoftware** [comment] 2017-06-03 19:29
The link was working earlier in the week.  It may come back in a while.  I don't think it's that old that they'd just remove it.

I could add it as a check but it's only the standalone GUI that's affected.  If you've got VS 2017 installed, the package work as expected.  I'm curious as to why you'd use the standalone GUI rather than the VS package.

**Comment by cezarypiatek** [comment] 2017-06-10 10:52
The link to MS Build Tools 2015 is not working anymore. I was able to download MS Build Tools 2015 using MSDN subscription from here https://my.visualstudio.com/downloads?wt.mc_id=o~msft~vscom~older-downloads&campaign=o~msft~vscom~older-downloads

@EWSoftware, Is there any chance to port SHFB to MS Build 2017 or to make it version agnostic?

**Comment by EWSoftware** [comment] 2017-06-10 18:44
The only thing having an issue is the standalone GUI.  I cannot update it to MSBuild 15.0 used by VS 2017 without dropping support for VS 2015 which I don't want to do yet.  If you've got VS2017, use the VS package.  If that's not an option fall back to the prior release for the time being.

I did not distribute the assemblies referenced by the standalone GUI since I didn't think it was necessary.  I can probably distribute them for use with the GUI as long as they don't break anything related to use within Visual Studio.

**Comment by EWSoftware** [comment] 2017-09-12 16:58
Duplicate of #467

**Closed by EWSoftware** 2017-09-12 16:58 UTC
