### ISSUE TITLE
Intellisence doesn't propose <inheritdoc/>

### ISSUE THREAD

**Issue by koryukov** [EWSoftware/SHFB#726] opened 2019-07-05 09:33 UTC
### Environment

**OS:** Windows 7 Pro  SP1
**IDE:** Microsoft Visual Studio Community 2019 16.1.5  
**SHFB:** Sandcastle Help File Builder 2019.4.14.0  
**Project type:** Class Library (.NET Framework)
**Language**: C#

### Description

There is no [`<inheritdoc/>`][1] item in Visual Studio IntelliSense tooltip:  

![IntelliSense tooltip](https://user-images.githubusercontent.com/29269573/60711906-4caa0180-9f2f-11e9-8a3f-cb86033484d1.png)

Note, the element works correctly. The method documentation is inherited from the base type method.  The problem is only with IntelliSense.

I have tried to reinstall MAML Schema IntelliSense for Visual Studio but the problem still remains.

[1]: http://ewsoftware.github.io/XMLCommentsGuide/html/86453FFB-B978-4A2A-9EB5-70E118CA8073.htm

**Comment by EWSoftware** [comment] 2019-07-05 15:34
It's caused by a change in VS 2019 and none of the augmented completion set items are offered right now. Duplicate of #722.

**Closed by EWSoftware** 2019-07-05 15:34 UTC

**Comment by EWSoftware** [comment] 2019-10-28 02:17
This has been fixed by implementing a new extension for VS 2019.  See the [comments in issue #722](https://github.com/EWSoftware/SHFB/issues/722#issuecomment-546765070) for the link to it and other info.
