### ISSUE TITLE
Return of ValueTuple is not documented Properly

### ISSUE THREAD

**Issue by StevenBonePgh** [EWSoftware/SHFB#763] opened 2019-11-16 00:31 UTC
May be similar to #619. 
A method with the signature:
`public async Task<(string, SomeEnum)> DoWork(object thing)`
or alternatively
`public async Task<ValueTuple<string, SomeEnum>> DoWork(object thing)`
is being documented as
`public Task<()> DoWork(object thing)`
And the summary, parameters, return value, etc is all showing 'missing documentation'.  These are in multitargeted libraries for 4.5.2, 4.8, and netstandard and regardless of full framework selection it appears to always want to select 4.5.2 at build time. I get the same results under the cross-platform as I do 4.5.2.  Any suggestions, Eric?

**Comment by EWSoftware** [comment] 2019-11-16 20:39
Can you supply a small example that I can test with?

**Comment by StevenBonePgh** [comment] 2019-11-22 15:33
Eric, 
Please see the zip with the sample project. The `MyValueTuple` class demonstrates issues with documenting `ValueTuple`.

1. The property documentation does not show the types in the Syntax overview even when they are specified: Actual: `public () MyProperty { get; }` Expected: `public (string,int) MyProperty { get; }`
2. The property documentation shows the type as `ValueTuple<T1,T2>`. Expectation would be `ValueTuple<string,int>` The `DoNothing` and `DoNothingAsync` methods have same flaws as 1 and 2 above. Much worse, however, is that the summary, parameter, and return value all show documentation as 'missing'. The Method summary does not show that these methods take parameters. The cause of one of these issues may be that the summary documentation thinks the 'thing' parameter is a bool, not an object: `warning : BuildAssembler : warning : ShowMissingComponent: [M:ValueTupleSandcastleDemo.MyValueTuple.DoNothingAsync(System.Boolean)] Missing <summary> documentation`
3. If you enable the `#define` for `INCLUDE_BOOL_OVERLOAD`, things get even stranger. The method that takes the bool correctly appears in the summary as taking a bool parameter. The summary, return, and parameter documentation is all present. However, the method that takes an object is now missing from the documentation altogether.

[ValueTupleSandcastleDemo.zip](https://github.com/EWSoftware/SHFB/files/3880175/ValueTupleSandcastleDemo.zip)

**Comment by EWSoftware** [comment] 2019-11-23 21:15
I was able to duplicate the issue with the latest published release (v2019.11.17.0).  I suspect the issue is related to the existing tools being built against .NET 4.5 and perhaps it isn't finding the System.ValueTuple reference or the one included with SHFB is causing some issues.

Anyway, I've been upgrading all of the tools to .NET 4.7.2 in order to get them more up to date and, with my internal build, the correct output is being generated.  So, it will be fixed indirectly in the next release.

**Comment by EWSoftware** [comment] 2019-12-01 21:41
Fixed indirectly in commit 2dcf64e3cd1b3301b341cf122ffb5a0a7c304e3a through update to .NET 4.7.2.

**Closed by EWSoftware** 2019-12-01 21:41 UTC
