### ISSUE TITLE
Support for project.json

### ISSUE THREAD

**Issue by nbarbettini** [EWSoftware/SHFB#255] opened 2016-02-18 22:12 UTC
SHFB doesn't currently support DNX projects (project.json or .xproj). Is there any workaround or way to get SHFB to recognize these newer projects?

**Comment by EWSoftware** [comment] 2016-02-18 22:35
Assuming they are website projects of some sort, they probably can't be supported directly.  If they're like other website projects, you may be able to use the [web code providers](http://ewsoftware.github.io/EWSoftwareCodeDom/html/40ba6bda-95d6-4a64-834f-f7cedcb589d1.htm) to generate XML comments files when then assemblies are created.

If you can get a set of assemblies and XML comments files, you can add them as documentation sources and build a help file from them.  Less convenient than using the project as the documentation source but the end result is the same.

If you can tell me how to create such a project, I'll take a look at them to see if anything can be done to support them.

**Comment by nbarbettini** [comment] 2016-02-19 16:52
Thanks for the reply! That makes sense.

The projects are the newer style used in DNX, .NET CoreCLR, and ASP.NET Core 1.0 (quite the alphabet soup). It includes but isn't limited to web projects. I'm building a class library, for example. There's a "Hello World" example here: https://dotnet.github.io/getting-started/

Looks like XML file generation hasn't been implemented yet: https://github.com/dotnet/cli/issues/585
Which explains why SHFB is having trouble. I'll look into the web code providers and see if I can get that working.

**Comment by muqeet-khan** [comment] 2016-03-03 17:19
@nbarbettini XML documentation can be generated at least in an xproj project by having 

```
    "compilationOptions": {
       .......
        "xmlDoc": true,
        "nowarn": [ "CS1591" ]
    },
```
in your project.json, and, you will have to select `produce output on build` in your build properties before you do a build. Then in your artifacts folder you will see the XML generated as usual.

**Comment by nbarbettini** [comment] 2016-03-03 17:24
@muqeet-khan Awesome, thanks!

**Comment by StefH** [comment] 2016-05-22 18:11
However, the new netstandard 1.x is not present in the 'Framework' list.

And while building the output, this error is displayed:

```
Project "C:\temp\Help\Working\GenerateRefInfo.proj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "obj\Debug\".
GenerateRefInfo:
  MRefBuilder (v2016.4.9.0)
  Copyright ¸ 2006-2016, Microsoft Corporation, All Rights Reserved.
  Portions Copyright ¸ 2006-2016, Eric Woodruff, All Rights Reserved.
  Loaded 1 assemblies for reflection and 1 dependency assemblies.
MRefBuilder : error : Unresolved assembly reference: System.Runtime (System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a) required by System.Linq.Dynamic.Core [C:\temp\Help\Working\GenerateRefInfo.proj]
    Last step completed in 00:00:01,4067
-------------------------------

SHFB: Error BE0043: Unexpected error detected in last build step.  See build log for details.
   at SandcastleBuilder.Utils.BuildEngine.TaskRunner.Run(String processFilename, String targetFile, String arguments)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()
```

**Comment by EWSoftware** [comment] 2016-05-22 19:09
I don't know what "netstandard 1.x" is.  Based on the error, you probably want to select .NET for Universal Windows or .NET Portable Library 5.0.  If you use the project or solution as the documentation source it should tell you what it finds and will switch the framework if it can if you choose the wrong one.

**Comment by StefH** [comment] 2016-05-22 19:47
https://blogs.msdn.microsoft.com/dotnet/2016/05/16/announcing-net-core-rc2/

http://dotnet.github.io/docs/core-concepts/libraries/libraries-with-cli.html

**Comment by EWSoftware** [comment] 2016-05-22 22:39
I give up.  Keeping track of all the framework flavors that keep popping up is a losing battle.  In this case, since the version on the assembly it's complaining about matches the Universal and the portable ones noted above, I'd try those.  If they don't work, you can have a go at [creating your own reflection data set](http://ewsoftware.github.io/SHFB/html/032f1fab-6625-4ffb-9316-57fb3e4a03ff.htm).

**Comment by EWSoftware** [comment] 2016-05-22 22:54
All things considered, is there any point in spending time on supporting .xproj/project.json files?  As I recall, I think I read somewhere that they are going to be phased out in favor of going back to standard MSBuild projects.

**Comment by StefH** [comment] 2016-05-23 06:26
Indeed, maybe it's better for this project to wait on the final way of building.

For me, this is not blocking because I also define other frameworks beside the netstandard, like net46 which is supported perfectly in your tool.

**Comment by jedielson** [comment] 2016-08-24 18:55
Hi Everybody.

With the RTM of .Net Core last june, is there any plan to continue this?

**Comment by EWSoftware** [comment] 2016-08-24 19:09
If you're referring to project.json, I have no immediate plans to support it.  As far as I know it's still going away so there's not much point.

If you're referring to .NETCore, it is supported unless you've got VS 2015 Update 3 which changes the folder structure of the .NETCore/.NETPortable reference assemblies thus breaking the reflection data support in SHFB.  That'll be fixed in the next release which I plan on publishing in a few weeks.

**Comment by jedielson** [comment] 2016-08-25 19:10
> If you're referring to .NETCore, it is supported unless you've got VS 2015 Update 3 which changes the folder structure of the .NETCore/.NETPortable reference assemblies thus breaking the reflection data support in SHFB. That'll be fixed in the next release which I plan on publishing in a few weeks.

Well, my interest is in generate docs to my .Net Core Standartd Libraries.
If it means that I'll be able to generate docs to these Libraries, then it's awesome!

**Comment by StefH** [comment] 2016-08-25 20:20
My library targets net46 and netstandard, so i can still use this project.

**Comment by EWSoftware** [comment] 2016-08-25 21:46
Can you provide an example?

**Comment by shibaev** [comment] 2016-08-28 13:26
> If you're referring to .NETCore, it is supported unless you've got VS 2015 Update 3 which changes the folder structure of the .NETCore/.NETPortable reference assemblies thus breaking the reflection data support in SHFB. That'll be fixed in the next release which I plan on publishing in a few weeks.

@EWSoftware, could you please also add ".NET Standard 1.*" or ".NET Platform Standard 1.*" to the "Framework version" dropdown?

**Comment by StefH** [comment] 2016-08-31 10:56
My project targets net46 and netstandard, example here https://github.com/StefH/System.Linq.Dynamic.Core

So I **can** still use this project to build help files.

**Comment by EWSoftware** [comment] 2016-08-31 17:48
Thanks for the clarification.  I find this netstandard stuff confusing.  I guess I'll just wait and see what happens.  If something doesn't work, then I'll get an example and figure out how to make it work.

**Comment by DecaTec** [comment] 2017-03-15 12:55
I know that this issue is quite old, but...

Using Visual Studio 2017 and SHFB v2017.1.28.0, I'm trying to generate help files for a .NETStandard 1.1 project. I always get error BE0073, no matter what framework version I'm using in the SHFB project's properties. Even the .NETCore stuff won't work.

Is there any workaround available yet?

**Comment by StefH** [comment] 2017-03-15 14:09
@decatec you also here 😃

**Comment by EWSoftware** [comment] 2017-03-15 15:21
@DecaTec: As noted above, if you can supply an example I can use to duplicate the problem, I'll look into it.
I don't do .NETCore/.NETStandard development so I'm not familiar with all the stuff that has to be installed or what everyone may or may not be using.  Getting an example is better than me trying to dummy something up when I don't know what's involved in reproducing the error.

**Comment by DecaTec** [comment] 2017-03-15 17:03
@StefH Sure - as long time user of SHFB trying to cope with netstandard :smiley:

@EWSoftware No problem, sample is here: https://github.com/DecaTec/Portable-WebDAV-Library/tree/netstandard
The SHFB project is already added. I only had to disable the project being built in release configuration (you'll have to enable it again). Hope this helps. If you need any more info, please just ask. I'll do my best to sort things out.

**Comment by DecaTec** [comment] 2017-03-19 12:20
Is the sample sufficient for your purpose?

In this case /as I understand it), it should be perfectly valid to use the ".NET Framework 4.5", as it implements .NET Standard 1.1, although the project's taget is not NetFx 4.5.

**Comment by EWSoftware** [comment] 2017-03-19 17:35
Yes, it's fine.  It's currently an unrecognized framework type.  I need to either add support for it or just redirect it to something equivalent.

**Comment by DecaTec** [comment] 2017-03-19 19:53
OK, great.
In the meantime I was pointed to a workaround. It works, but is rather odd:
I've created a 'dummy' project targeting .NET Framework 4.5. Then I've linked all the files from the netstandard project into the dummy project. Building the SHFB project against that dummy project gives me the correct documentation.

**Comment by EWSoftware** [comment] 2017-03-19 22:39
.NETStandard is a bit odd.  Its outputs seems to work regardless of the framework chosen in the SHFB project so that's pretty much how I've handled it.  If it sees .NETStandard as the documentation source's project type, it defers to the framework selection in the SHFB project and calls it good.

If it turns out that it's not a good match and it gets assembly version mismatches, the most likely course of action will probably be to choose a more appropriate framework version in the SHFB project (i.e. .NETCore rather than .NETFramework).  That's just a theory but we'll see how it plays out.

**Comment by EWSoftware** [comment] 2017-03-20 02:24
Well, not so straightforward as usual.  If you chose a different target framework like .NETStandard 1.6, it doesn't find all the necessary reference assemblies like it does if .NETStandard1.1 is selected.  It's basically because everything is distributed as NuGet packages and the SDK folder I used to create the reflection data set info seems to change with every new release or update to Visual Studio or just goes away.

For now, I've just added a workaround to try and redirect missing assemblies to know assemblies and for any it doesn't find that are framework assemblies, it ignores them.  The inherited base framework class info will probably be incomplete but it will build the documentation.

The longer term solution is to come up with a way to handle the frameworks that are distributed as NuGet packages dynamically rather than using fixed sets of reflection data.  That's probably going to take a while.

**Comment by EWSoftware** [comment] 2017-04-09 01:27
Since it does appear that project.json files [are deprecated](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json-to-csproj), I'm closing this work item.

See work item #440 for updates on support for the replacement project format for .NETCore/.NETStandard projects.

**Closed by EWSoftware** 2017-04-09 01:27 UTC
Labels: OnHold
