### ISSUE TITLE
BUILD FAILED: The tools version "15.0" is unrecognized. Available tools versions are "14.0", "2.0", "3.5", "4.0".  

### ISSUE THREAD

**Issue by Tianwen9579** [EWSoftware/SHFB#797] opened 2020-05-07 06:39 UTC
I changed all the ToolsVersion of the project from 15.0 to 14.0 but it still didn't work
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

**Comment by Tianwen9579** [comment] 2020-05-07 06:55
The following is the detailed error message
 在 Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   在 Microsoft.Build.Evaluation.Project.Data.InitializeForEvaluation(IToolsetProvider toolsetProvider, IFileSystem fileSystem)
   在 Microsoft.Build.Evaluation.Evaluator`4..ctor(IEvaluatorData`4 data, ProjectRootElement projectRootElement, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext, Boolean profileEvaluation)
   在 Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   在 Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   在 Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   在 Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   在 SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

**Comment by Tianwen9579** [comment] 2020-05-07 07:23
The wrong place is 
\Help\Working\GenerateRefInfo.proj

**Comment by EWSoftware** [comment] 2020-05-07 14:07
Duplicate of #790.  Either use Visual Studio to build the project or go back to the prior release until the issue is fixed.

**Closed by EWSoftware** 2020-05-07 14:07 UTC
Labels: Duplicate

**Comment by Tianwen9579** [comment] 2020-05-08 09:20
Thanks @EWSoftware 
I've tried it. This version will do
SHFBInstaller_v2019.4.7.0

**Comment by VBWebprofi** [comment] 2020-07-23 19:08
MSBuild 15.0 is part of VS 2017. You can download on

https://my.visualstudio.com/Downloads?q=visual%20studio%202017&wt.mc_id=o~msft~vscom~older-downloads .

For Installation select ``Visual C++ Buildtools`` and unselect on right pane all optionals
